### ISSUE TITLE
Need some contributors for this project 

### ISSUE THREAD

**Issue by manojkumar2608** [manojkumar2608/Animation-Library#1]
We need some collaborators for the project . If anyone intrested . join Us

**Comment by ManojkumarChandrasekar** [comment]
I like to contribute to this library . I'm Manojkumar . Full Stack Web Dev and Digital Marketer

**Comment by manojkumar2608** [comment]
Thank you for your support

**Comment by ManojkumarChandrasekar** [comment]
Nerver Mind

**Comment by manojkumar2608** [comment]
👍
